### ISSUE TITLE
The amazon "Bill of Mat4rials" registry for project is no longer in alignment with project

### ISSUE THREAD

**Issue by dwmcallister** [awslabs/simplerobotservice#3]
From the README.md

"Bill of Materials

Complete list: http://www.amazon.com/registry/giftlist/10S3G6J5UJBXO"

yields a single item.
![image](https://cloud.githubusercontent.com/assets/1463172/21782383/1b89b45c-d668-11e6-820f-b374c7f72832.png)

A complete bill of materials for the project would be desirable.

**Comment by anupamm** [comment]
@dwmcallister  Thanks for pointing, we have removed the non working Bill of Materials link
